# frozen_string_literal: true

require "spec_helper"

RSpec.describe Mana::Compiler do
  let(:cache_dir) { Dir.mktmpdir("mana_test_cache") }

  before do
    described_class.cache_dir = cache_dir
    described_class.clear!
    Mana.config.api_key = "test-key"
  end

  after do
    FileUtils.rm_rf(cache_dir)
  end

  describe ".generate" do
    it "calls the engine and returns generated code" do
      stub_anthropic_sequence(
        [{ type: "tool_use", id: "t1", name: "write_var",
           input: { "name" => "code", "value" => "def greet(name)\n  \"Hello, \#{name}\"\nend" } }],
        [{ type: "tool_use", id: "t2", name: "done", input: {} }]
      )

      result = described_class.generate(:greet, "name", "greet the person by name")
      expect(result).to include("def greet")
      expect(result).to include("Hello")
    end

    it "unescapes literal \\n from LLM-generated code" do
      stub_anthropic_sequence(
        [{ type: "tool_use", id: "t1", name: "write_var",
           input: { "name" => "code", "value" => 'def add(a, b)\n  a + b\nend' } }],
        [{ type: "tool_use", id: "t2", name: "done", input: {} }]
      )

      result = described_class.generate(:add, "a, b", "add two numbers")
      expect(result).to include("def add(a, b)\n  a + b\nend")
      expect(result).not_to include('\\n')
    end
  end

  describe ".write_cache" do
    it "writes a .rb file to the cache directory" do
      source = "def add(a, b)\n  a + b\nend"
      path = described_class.write_cache(:add, source)

      expect(File.exist?(path)).to be true
      content = File.read(path)
      expect(content).to include("Auto-generated by ruby-mana")
      expect(content).to include("def add(a, b)")
    end

    it "includes owner prefix for class methods" do
      source = "def multiply(a, b)\n  a * b\nend"
      path = described_class.write_cache(:multiply, source, String)

      expect(File.basename(path)).to eq("string_multiply.rb")
    end
  end

  describe ".source" do
    it "returns nil for uncompiled methods" do
      expect(described_class.source(:nonexistent)).to be_nil
    end

    it "returns source after compilation" do
      code = "def test_method\n  42\nend"
      described_class.registry["test_method"] = code
      expect(described_class.source(:test_method)).to eq(code)
    end
  end

  describe ".clear!" do
    it "removes cache directory and clears registry" do
      FileUtils.mkdir_p(cache_dir)
      File.write(File.join(cache_dir, "test.rb"), "# test")
      described_class.registry["test"] = "code"

      described_class.clear!

      expect(Dir.exist?(cache_dir)).to be false
      expect(described_class.registry).to be_empty
    end
  end

  describe ".compile" do
    it "wraps a method for lazy compilation" do
      klass = Class.new do
        def square(n)
          ~"return n squared"
        end
      end

      # Mock generate to avoid full engine/HTTP stack
      generated_code = "def square(n)\n  n * n\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :square)

      obj = klass.new
      result = obj.square(5)
      expect(result).to eq(25)

      # Verify cache file was written
      cache_files = Dir.glob(File.join(cache_dir, "*.rb"))
      expect(cache_files.length).to eq(1)
      expect(File.read(cache_files.first)).to include("n * n")

      # Verify source is accessible
      key = "#{klass}#square"
      expect(described_class.registry[key]).to eq(generated_code)
    end

    it "preserves private visibility" do
      klass = Class.new do
        private

        def secret_method(n)
          ~"return n"
        end
      end

      generated_code = "def secret_method(n)\n  n\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :secret_method)

      obj = klass.new
      # Should be private — not callable externally
      expect { obj.secret_method(5) }.to raise_error(NoMethodError, /private/)
      # But callable internally via send
      expect(obj.send(:secret_method, 5)).to eq(5)
    end

    it "preserves protected visibility" do
      klass = Class.new do
        protected

        def protected_method(n)
          ~"return n"
        end
      end

      generated_code = "def protected_method(n)\n  n\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :protected_method)

      obj = klass.new
      expect { obj.protected_method(5) }.to raise_error(NoMethodError, /protected/)
      expect(obj.send(:protected_method, 5)).to eq(5)
    end

    it "keeps public methods public" do
      klass = Class.new do
        def public_method(n)
          ~"return n"
        end
      end

      generated_code = "def public_method(n)\n  n\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :public_method)

      obj = klass.new
      expect(obj.public_method(5)).to eq(5)
    end
  end

  describe "cache hit / miss" do
    it "uses cache when prompt_hash matches (no LLM call)" do
      klass = Class.new do
        def cached_method(n)
          ~"return n doubled"
        end
      end

      original = klass.instance_method(:cached_method)
      params_desc = described_class.send(:describe_params, original)
      prompt = described_class.send(:extract_prompt, original)
      source_file = original.source_location&.first
      sibling_methods = begin
        Mana::Introspect.methods_from_file(source_file)
          .reject { |m| m[:name] == "cached_method" }
          .map { |m| "#{m[:name]}(#{m[:params].join(',')})" }
          .sort.join(";")
      rescue
        ""
      end
      prompt_hash = Digest::SHA256.hexdigest("#{Mana::VERSION}:#{RUBY_VERSION}:cached_method:#{params_desc}:#{prompt}:#{sibling_methods}")[0, 16]

      # Pre-populate cache with matching prompt_hash
      cache_path = described_class.cache_file_path(:cached_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: #{prompt_hash}\n# frozen_string_literal: true\n\ndef cached_method(n)\n  n * 2\nend\n")

      expect(described_class).not_to receive(:generate)
      described_class.compile(klass, :cached_method)

      obj = klass.new
      expect(obj.cached_method(5)).to eq(10)
    end

    it "regenerates when prompt_hash does not match (cache miss)" do
      klass = Class.new do
        def stale_method(n)
          ~"return n tripled"
        end
      end

      original = klass.instance_method(:stale_method)
      source_file = original.source_location&.first
      cache_path = described_class.cache_file_path(:stale_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: wrong_hash_here\n# frozen_string_literal: true\n\ndef stale_method(n)\n  n * 2\nend\n")

      generated_code = "def stale_method(n)\n  n * 3\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :stale_method)

      obj = klass.new
      expect(obj.stale_method(5)).to eq(15)
      expect(described_class).to have_received(:generate)
    end

    it "extracts prompt from instruction sequence when source file unavailable (IRB/eval)" do
      # Define the method via eval so source file doesn't exist
      klass = Class.new
      klass.class_eval('def iseq_method(n); ~"return n doubled"; end', "(irb)", 1)

      original = klass.instance_method(:iseq_method)
      # File path is "(irb)" — extract_prompt falls through to iseq extraction
      prompt = described_class.send(:extract_prompt, original)
      expect(prompt).to eq("return n doubled")
    end

    it "extracts multi-line prompt from instruction sequence" do
      klass = Class.new
      klass.class_eval("def multi_method(n)\n  ~\"line one\\nline two\\nline three\"\nend", "(irb)", 1)

      original = klass.instance_method(:multi_method)
      prompt = described_class.send(:extract_prompt, original)
      expect(prompt).to include("line one")
      expect(prompt).to include("line two")
      expect(prompt).to include("line three")
    end

    it "auto-invalidates cache when prompt changes (even without source file)" do
      klass = Class.new do
        def changing_method(n)
          ~"return n tripled"
        end
      end

      # Prompt is "return n tripled" — compute its hash
      params_desc = described_class.send(:describe_params, klass.instance_method(:changing_method))
      prompt = described_class.send(:extract_prompt, klass.instance_method(:changing_method))
      current_hash = Digest::SHA256.hexdigest("#{Mana::VERSION}:#{RUBY_VERSION}:changing_method:#{params_desc}:#{prompt}")[0, 16]

      # Pre-populate cache with DIFFERENT hash (simulates old prompt)
      source_file = klass.instance_method(:changing_method).source_location&.first
      cache_path = described_class.cache_file_path(:changing_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: old_stale_hash\n\ndef changing_method(n)\n  n * 99\nend\n")

      generated_code = "def changing_method(n)\n  n * 3\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :changing_method)

      obj = klass.new
      expect(obj.changing_method(5)).to eq(15)  # regenerated, not stale cache
      expect(described_class).to have_received(:generate)
    end
  end

  describe ".extract_prompt" do
    it "extracts prompt from ~\"...\" expression" do
      tmpfile = Tempfile.new(["mana_test", ".rb"])
      tmpfile.write("def foo\n  ~\"my prompt\"\nend\n")
      tmpfile.rewind

      # Create a class that has a method at that source location
      klass = Class.new
      # We can test via the private method directly with a mock unbound method
      mock_method = double("unbound_method", source_location: [tmpfile.path, 1])
      result = described_class.send(:extract_prompt, mock_method)
      expect(result).to eq("my prompt")
    ensure
      tmpfile.close
      tmpfile.unlink
    end

    it "extracts multi-line prompt" do
      tmpfile = Tempfile.new(["mana_test", ".rb"])
      tmpfile.write(<<~RUBY)
        def bar(n)
          ~"line one
          line two
          line three"
        end
      RUBY
      tmpfile.rewind

      mock_method = double("unbound_method", source_location: [tmpfile.path, 1])
      result = described_class.send(:extract_prompt, mock_method)
      expect(result).to include("line one")
      expect(result).to include("line two")
      expect(result).to include("line three")
    ensure
      tmpfile.close
      tmpfile.unlink
    end

    it "handles string with escaped quotes" do
      tmpfile = Tempfile.new(["mana_test", ".rb"])
      tmpfile.write("def baz\n  ~\"return \\\"hello\\\" world\"\nend\n")
      tmpfile.rewind

      mock_method = double("unbound_method", source_location: [tmpfile.path, 1])
      result = described_class.send(:extract_prompt, mock_method)
      expect(result).to include("hello")
      expect(result).to include("world")
    ensure
      tmpfile.close
      tmpfile.unlink
    end

    it "not confused by if/def keywords inside strings" do
      tmpfile = Tempfile.new(["mana_test", ".rb"])
      tmpfile.write(<<~RUBY)
        def tricky
          ~"if the def is end, return begin"
        end
      RUBY
      tmpfile.rewind

      mock_method = double("unbound_method", source_location: [tmpfile.path, 1])
      result = described_class.send(:extract_prompt, mock_method)
      expect(result).to eq("if the def is end, return begin")
    ensure
      tmpfile.close
      tmpfile.unlink
    end
  end

  describe ".cache_file_path" do
    it "slugifies source file path in filename" do
      path = described_class.cache_file_path(:calculate, nil, source_file: "#{Dir.pwd}/lib/foo/bar.rb")
      expect(File.basename(path)).to eq("lib_foo_bar_calculate.rb")
    end
  end

  describe ".underscore" do
    it "converts MyClass::Foo to my_class_foo" do
      expect(described_class.send(:underscore, "MyClass::Foo")).to eq("my_class_foo")
    end

    it "returns 'anonymous' for nil" do
      expect(described_class.send(:underscore, nil)).to eq("anonymous")
    end
  end

  describe "describe_params" do
    it "handles various parameter types" do
      klass = Class.new do
        def complex(a, b = 1, *rest, key:, opt: nil, **kwargs, &block); end
      end

      method = klass.instance_method(:complex)
      result = described_class.send(:describe_params, method)
      expect(result).to eq("a, b=nil, *rest, key:, opt: nil, **kwargs, &block")
    end

    it "handles no parameters" do
      klass = Class.new do
        def simple; end
      end

      method = klass.instance_method(:simple)
      result = described_class.send(:describe_params, method)
      expect(result).to eq("")
    end

    it "handles **nil (nokey) parameter" do
      klass = Class.new do
        def no_keywords(a, **nil); end
      end

      method = klass.instance_method(:no_keywords)
      result = described_class.send(:describe_params, method)
      expect(result).to eq("a")
      expect(result).not_to include("nil")
    end
  end

  describe ".scrub_orphaned_caches" do
    # Set up a fake source file with only one mana-def method, plus a
    # cache directory containing files for that method AND a stale one
    # for a method that used to exist but no longer does.
    let(:source_dir) { Dir.mktmpdir("mana_test_source") }
    let(:source_file) { File.join(source_dir, "fake_src.rb") }

    before do
      FileUtils.mkdir_p(cache_dir) # `clear!` in outer before removed it
      File.write(source_file, <<~RUBY)
        mana def keeper
          ~"keep me"
        end
      RUBY
    end

    after { FileUtils.rm_rf(source_dir) }

    def fake_cache(method_name, hash = "abc123def4567890")
      rel = source_file.sub("#{Dir.pwd}/", "").sub(/\.rb$/, "")
      prefix = rel.tr("/", "_")
      path = File.join(cache_dir, "#{prefix}_#{method_name}.rb")
      File.write(path, "# Auto-generated by ruby-mana v0.5.14 | ruby 3.4.2 | prompt_hash: #{hash}\n# frozen_string_literal: true\n\ndef #{method_name}; end\n")
      path
    end

    it "removes cache files whose method no longer exists in the source" do
      keep = fake_cache("keeper")
      orphan = fake_cache("deleted_method")

      removed = described_class.scrub_orphaned_caches(source_file)

      expect(File.exist?(keep)).to be true
      expect(File.exist?(orphan)).to be false
      expect(removed).to eq([orphan])
    end

    it "is a no-op when introspection fails (returns [], deletes nothing)" do
      allow(Mana::Introspect).to receive(:methods_from_file).and_raise(StandardError, "boom")
      orphan = fake_cache("deleted_method")
      expect(described_class.scrub_orphaned_caches(source_file)).to eq([])
      expect(File.exist?(orphan)).to be true
    end

    it "returns [] when source_file does not exist" do
      expect(described_class.scrub_orphaned_caches("/nonexistent/path.rb")).to eq([])
    end

    it "returns [] when cache_dir does not exist" do
      FileUtils.rm_rf(cache_dir)
      expect(described_class.scrub_orphaned_caches(source_file)).to eq([])
    end

    it "preserves cache files for unrelated source files" do
      # A cache file from a totally different source — must not be touched.
      unrelated = File.join(cache_dir, "other_src_foo.rb")
      File.write(unrelated, "# header\ndef foo; end\n")
      described_class.scrub_orphaned_caches(source_file)
      expect(File.exist?(unrelated)).to be true
    end
  end

  describe ".scrub_orphaned_caches_once" do
    let(:source_dir) { Dir.mktmpdir("mana_test_source2") }
    let(:source_file) { File.join(source_dir, "memo_src.rb") }

    before do
      FileUtils.mkdir_p(cache_dir)
      File.write(source_file, "mana def x; ~\"x\"; end\n")
    end

    after { FileUtils.rm_rf(source_dir) }

    it "scrubs only on first call per source file" do
      expect(described_class).to receive(:scrub_orphaned_caches).with(source_file).once.and_call_original
      described_class.scrub_orphaned_caches_once(source_file)
      described_class.scrub_orphaned_caches_once(source_file)
      described_class.scrub_orphaned_caches_once(source_file)
    end

    it "scrubs again after clear! resets the memo" do
      expect(described_class).to receive(:scrub_orphaned_caches).twice.and_call_original
      described_class.scrub_orphaned_caches_once(source_file)
      described_class.clear!
      described_class.scrub_orphaned_caches_once(source_file)
    end
  end
end
